# -- AtomiCloud Service Tree. See [ServiceTree](https://atomicloud.larksuite.com/wiki/OkfJwTXGFiMJkrk6W3RuwRrZs64?theme=DARK&contentTheme=DARK#MHw5d76uDo2tBLx86cduFQMRsBb)
serviceTree:
  platform: &platform sulfoxide
  service: &service sulfur
  layer: &layer "1"

# -- Kubernetes labels and annotations, following Service Tree
tags: &tags
  atomi.cloud/platform: *platform
  atomi.cloud/service: *service
  atomi.cloud/layer: *layer

# -- Cert Manager configuration. See [Cert Manager Helm Chart](https://artifacthub.io/packages/helm/cert-manager/cert-manager)
cert-manager:
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "topology.kubernetes.io/zone"
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          <<: *tags
          atomi.cloud/module: operator
  serviceAccount:
    annotations:
      <<: *tags
      atomi.cloud/module: operator
    labels:
      <<: *tags
      atomi.cloud/module: operator
  startupapicheck:
    jobAnnotations:
      <<: *tags
      atomi.cloud/module: satupapicheck
    podAnnotations:
      <<: *tags
      atomi.cloud/module: satupapicheck
    podLabels:
      <<: *tags
      atomi.cloud/module: satupapicheck
    resources:
      limits:
        cpu: 10m
        memory: 256Mi
      requests:
        cpu: 5m
        memory: 64Mi
  resources:
    limits:
      cpu: 10m
      memory: 256Mi
    requests:
      cpu: 5m
      memory: 64Mi
  podLabels:
    <<: *tags
    atomi.cloud/module: operator
  podAnnotations:
    <<: *tags
    atomi.cloud/module: operator
  cainjector:
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            <<: *tags
            atomi.cloud/module: cainjector
    resources:
      limits:
        cpu: 10m
        memory: 256Mi
      requests:
        cpu: 5m
        memory: 64Mi
    podAnnotations:
      <<: *tags
      atomi.cloud/module: cainjector
    deploymentAnnotations:
      <<: *tags
      atomi.cloud/module: cainjector
    podLabels:
      <<: *tags
      atomi.cloud/module: cainjector
  webhook:
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            <<: *tags
            atomi.cloud/module: webhook
    resources:
      limits:
        cpu: 10m
        memory: 256Mi
      requests:
        cpu: 5m
        memory: 64Mi
    podLabels:
      <<: *tags
      atomi.cloud/module: webhook
    deploymentAnnotations:
      <<: *tags
      atomi.cloud/module: webhook
    podAnnotations:
      <<: *tags
      atomi.cloud/module: webhook
  securityContext:
    fsGroup: 1001
  installCRDs: true
  prometheus:
    enabled: false
